// Code to convert Excel dates to JS dates and vice versa.

// Excel uses a date serial system which starts from the number
// 1 and is incremented by 1 for each increment afterwards. The
// number 1 represents January 1 1900.

// JavaScript dates are based on the unix date system. This is
// based on the number of millseconds that have elapsed since
// the unix epoch. The unix epoch is January 1st 1970

// The jsDateToExcelDate and excelDateToJSDate functions convert 
//dates as their names imply provided the correct input. Under 
// the hood, they both utilize the excelJsDateConvertor function.

// The code also include two string enums for locale and
// timezone to assist with this functionality. These were
// created to assist in providing intellisense when utilizing
// the date functionality.

// The doWork procedure shows an example of how these
// procedures might be used to convert to and from
// Excel dates and JS dates.

// Representing time is a bit trickier. You can represent hours
// as the number of hours * 60 (minutes) / 1440 (minutesInaDay)
// I will try to update this project in the future to also work
// with time as well.


function main(workbook: ExcelScript.Workbook) {
    doWork()
  }
  
  function doWork(){
    let today = new Date()
    let todayExcelDate: number = jsDateToExcelDate(today)
    console.log(`JS to Serial is ${todayExcelDate}`)
    let todayJsDate: Date = excelDateToJSDate(todayExcelDate)
    console.log(`Serial to JS is ${todayJsDate.toLocaleDateString(locale.en_US, { timeZone: timeZone.America_Los_Angeles })}`);
  }
  
  function jsDateToExcelDate(jsDate:Date): number {
    let excelDate : number = excelJSDateConvertor(jsDate) as number
    return excelDate;
  }
  
  function excelDateToJSDate(excelDate: number): Date {
    let jsDate: Date = excelJSDateConvertor(excelDate) as Date
    return jsDate;
  }
  
  function excelJSDateConvertor(date: number | Date): number | Date {
    //code adapted from here: https://stackoverflow.com/questions/16229494/converting-excel-date-serial-number-to-date-using-javascript
    const unixEpoch : number = 25569
    const hoursInADay: number = 24;
    const minutesInAnHour: number = 60;
    const secondsInAMinute: number = 60;
    const secondsInADay: number = hoursInADay * minutesInAnHour * secondsInAMinute;
    const millisecondsInADay: number = secondsInADay * 1000;
    let convertedDate: number|Date
  
    if (typeof date === "number") {
      //does the date need to have one substracted from it if it's greater than 61 per this question? https://stackoverflow.com/a/57184486/16864869
      //investigate later
      convertedDate = new Date(Math.floor((date - unixEpoch) * millisecondsInADay));
    } else if (date instanceof Date) {
      convertedDate = (date.getTime() / millisecondsInADay) + unixEpoch;
    }
  
    return convertedDate;
  }
  
  enum locale {
    //Code adapted from here: https://stackoverflow.com/a/9893752/16864869
    af_ZA = "af-ZA",
    am_ET = "am-ET",
    ar_AE = "ar-AE",
    ar_BH = "ar-BH",
    ar_DZ = "ar-DZ",
    ar_EG = "ar-EG",
    ar_IQ = "ar-IQ",
    ar_JO = "ar-JO",
    ar_KW = "ar-KW",
    ar_LB = "ar-LB",
    ar_LY = "ar-LY",
    ar_MA = "ar-MA",
    ar_OM = "ar-OM",
    ar_QA = "ar-QA",
    ar_SA = "ar-SA",
    ar_SY = "ar-SY",
    ar_TN = "ar-TN",
    ar_YE = "ar-YE",
    arn_CL = "arn-CL",
    as_IN = "as-IN",
    az_Cyrl_AZ = "az-Cyrl-AZ",
    az_Latn_AZ = "az-Latn-AZ",
    ba_RU = "ba-RU",
    be_BY = "be-BY",
    bg_BG = "bg-BG",
    bn_BD = "bn-BD",
    bn_IN = "bn-IN",
    bo_CN = "bo-CN",
    br_FR = "br-FR",
    bs_Cyrl_BA = "bs-Cyrl-BA",
    bs_Latn_BA = "bs-Latn-BA",
    ca_ES = "ca-ES",
    co_FR = "co-FR",
    cs_CZ = "cs-CZ",
    cy_GB = "cy-GB",
    da_DK = "da-DK",
    de_AT = "de-AT",
    de_CH = "de-CH",
    de_DE = "de-DE",
    de_LI = "de-LI",
    de_LU = "de-LU",
    dsb_DE = "dsb-DE",
    dv_MV = "dv-MV",
    el_GR = "el-GR",
    en_029 = "en-029",
    en_AU = "en-AU",
    en_BZ = "en-BZ",
    en_CA = "en-CA",
    en_GB = "en-GB",
    en_IE = "en-IE",
    en_IN = "en-IN",
    en_JM = "en-JM",
    en_MY = "en-MY",
    en_NZ = "en-NZ",
    en_PH = "en-PH",
    en_SG = "en-SG",
    en_TT = "en-TT",
    en_US = "en-US",
    en_ZA = "en-ZA",
    en_ZW = "en-ZW",
    es_AR = "es-AR",
    es_BO = "es-BO",
    es_CL = "es-CL",
    es_CO = "es-CO",
    es_CR = "es-CR",
    es_DO = "es-DO",
    es_EC = "es-EC",
    es_ES = "es-ES",
    es_GT = "es-GT",
    es_HN = "es-HN",
    es_MX = "es-MX",
    es_NI = "es-NI",
    es_PA = "es-PA",
    es_PE = "es-PE",
    es_PR = "es-PR",
    es_PY = "es-PY",
    es_SV = "es-SV",
    es_US = "es-US",
    es_UY = "es-UY",
    es_VE = "es-VE",
    et_EE = "et-EE",
    eu_ES = "eu-ES",
    fa_IR = "fa-IR",
    fi_FI = "fi-FI",
    fil_PH = "fil-PH",
    fo_FO = "fo-FO",
    fr_BE = "fr-BE",
    fr_CA = "fr-CA",
    fr_CH = "fr-CH",
    fr_FR = "fr-FR",
    fr_LU = "fr-LU",
    fr_MC = "fr-MC",
    fy_NL = "fy-NL",
    ga_IE = "ga-IE",
    gd_GB = "gd-GB",
    gl_ES = "gl-ES",
    gsw_FR = "gsw-FR",
    gu_IN = "gu-IN",
    ha_Latn_NG = "ha-Latn-NG",
    he_IL = "he-IL",
    hi_IN = "hi-IN",
    hr_BA = "hr-BA",
    hr_HR = "hr-HR",
    hsb_DE = "hsb-DE",
    hu_HU = "hu-HU",
    hy_AM = "hy-AM",
    id_ID = "id-ID",
    ig_NG = "ig-NG",
    ii_CN = "ii-CN",
    is_IS = "is-IS",
    it_CH = "it-CH",
    it_IT = "it-IT",
    iu_Cans_CA = "iu-Cans-CA",
    iu_Latn_CA = "iu-Latn-CA",
    ja_JP = "ja-JP",
    ka_GE = "ka-GE",
    kk_KZ = "kk-KZ",
    kl_GL = "kl-GL",
    km_KH = "km-KH",
    kn_IN = "kn-IN",
    ko_KR = "ko-KR",
    kok_IN = "kok-IN",
    ky_KG = "ky-KG",
    lb_LU = "lb-LU",
    lo_LA = "lo-LA",
    lt_LT = "lt-LT",
    lv_LV = "lv-LV",
    mi_NZ = "mi-NZ",
    mk_MK = "mk-MK",
    ml_IN = "ml-IN",
    mn_MN = "mn-MN",
    mn_Mong_CN = "mn-Mong-CN",
    moh_CA = "moh-CA",
    mr_IN = "mr-IN",
    ms_BN = "ms-BN",
    ms_MY = "ms-MY",
    mt_MT = "mt-MT",
    nb_NO = "nb-NO",
    ne_NP = "ne-NP",
    nl_BE = "nl-BE",
    nl_NL = "nl-NL",
    nn_NO = "nn-NO",
    nso_ZA = "nso-ZA",
    oc_FR = "oc-FR",
    or_IN = "or-IN",
    pa_IN = "pa-IN",
    pl_PL = "pl-PL",
    prs_AF = "prs-AF",
    ps_AF = "ps-AF",
    pt_BR = "pt-BR",
    pt_PT = "pt-PT",
    qut_GT = "qut-GT",
    quz_BO = "quz-BO",
    quz_EC = "quz-EC",
    quz_PE = "quz-PE",
    rm_CH = "rm-CH",
    ro_RO = "ro-RO",
    ru_RU = "ru-RU",
    rw_RW = "rw-RW",
    sa_IN = "sa-IN",
    sah_RU = "sah-RU",
    se_FI = "se-FI",
    se_NO = "se-NO",
    se_SE = "se-SE",
    si_LK = "si-LK",
    sk_SK = "sk-SK",
    sl_SI = "sl-SI",
    sma_NO = "sma-NO",
    sma_SE = "sma-SE",
    smj_NO = "smj-NO",
    smj_SE = "smj-SE",
    smn_FI = "smn-FI",
    sms_FI = "sms-FI",
    sq_AL = "sq-AL",
    sr_Cyrl_BA = "sr-Cyrl-BA",
    sr_Cyrl_CS = "sr-Cyrl-CS",
    sr_Cyrl_ME = "sr-Cyrl-ME",
    sr_Cyrl_RS = "sr-Cyrl-RS",
    sr_Latn_BA = "sr-Latn-BA",
    sr_Latn_CS = "sr-Latn-CS",
    sr_Latn_ME = "sr-Latn-ME",
    sr_Latn_RS = "sr-Latn-RS",
    sv_FI = "sv-FI",
    sv_SE = "sv-SE",
    sw_KE = "sw-KE",
    syr_SY = "syr-SY",
    ta_IN = "ta-IN",
    te_IN = "te-IN",
    tg_Cyrl_TJ = "tg-Cyrl-TJ",
    th_TH = "th-TH",
    tk_TM = "tk-TM",
    tn_ZA = "tn-ZA",
    tr_TR = "tr-TR",
    tt_RU = "tt-RU",
    tzm_Latn_DZ = "tzm-Latn-DZ",
    ug_CN = "ug-CN",
    uk_UA = "uk-UA",
    ur_PK = "ur-PK",
    uz_Cyrl_UZ = "uz-Cyrl-UZ",
    uz_Latn_UZ = "uz-Latn-UZ",
    vi_VN = "vi-VN",
    wo_SN = "wo-SN",
    xh_ZA = "xh-ZA",
    yo_NG = "yo-NG",
    zh_CN = "zh-CN",
    zh_HK = "zh-HK",
    zh_MO = "zh-MO",
    zh_SG = "zh-SG",
    zh_TW = "zh-TW",
    zu_ZA = "zu-ZA"
  }
  
  enum timeZone {
    //code adapted from here: https://stackoverflow.com/a/54500197/16864869
    Africa_Abidjan = "Africa/Abidjan",
    Africa_Accra = "Africa/Accra",
    Africa_Algiers = "Africa/Algiers",
    Africa_Bissau = "Africa/Bissau",
    Africa_Cairo = "Africa/Cairo",
    Africa_Casablanca = "Africa/Casablanca",
    Africa_Ceuta = "Africa/Ceuta",
    Africa_El_Aaiun = "Africa/El_Aaiun",
    Africa_Johannesburg = "Africa/Johannesburg",
    Africa_Juba = "Africa/Juba",
    Africa_Khartoum = "Africa/Khartoum",
    Africa_Lagos = "Africa/Lagos",
    Africa_Maputo = "Africa/Maputo",
    Africa_Monrovia = "Africa/Monrovia",
    Africa_Nairobi = "Africa/Nairobi",
    Africa_Ndjamena = "Africa/Ndjamena",
    Africa_Sao_Tome = "Africa/Sao_Tome",
    Africa_Tripoli = "Africa/Tripoli",
    Africa_Tunis = "Africa/Tunis",
    Africa_Windhoek = "Africa/Windhoek",
    America_Adak = "America/Adak",
    America_Anchorage = "America/Anchorage",
    America_Araguaina = "America/Araguaina",
    America_Argentina_Buenos_Aires = "America/Argentina/Buenos_Aires",
    America_Argentina_Catamarca = "America/Argentina/Catamarca",
    America_Argentina_Cordoba = "America/Argentina/Cordoba",
    America_Argentina_Jujuy = "America/Argentina/Jujuy",
    America_Argentina_La_Rioja = "America/Argentina/La_Rioja",
    America_Argentina_Mendoza = "America/Argentina/Mendoza",
    America_Argentina_Rio_Gallegos = "America/Argentina/Rio_Gallegos",
    America_Argentina_Salta = "America/Argentina/Salta",
    America_Argentina_San_Juan = "America/Argentina/San_Juan",
    America_Argentina_San_Luis = "America/Argentina/San_Luis",
    America_Argentina_Tucuman = "America/Argentina/Tucuman",
    America_Argentina_Ushuaia = "America/Argentina/Ushuaia",
    America_Asuncion = "America/Asuncion",
    America_Atikokan = "America/Atikokan",
    America_Bahia = "America/Bahia",
    America_Bahia_Banderas = "America/Bahia_Banderas",
    America_Barbados = "America/Barbados",
    America_Belem = "America/Belem",
    America_Belize = "America/Belize",
    America_Blanc_Sablon = "America/Blanc-Sablon",
      America_Boa_Vista = "America/Boa_Vista",
      America_Bogota = "America/Bogota",
      America_Boise = "America/Boise",
      America_Cambridge_Bay = "America/Cambridge_Bay",
      America_Campo_Grande = "America/Campo_Grande",
      America_Cancun = "America/Cancun",
      America_Caracas = "America/Caracas",
      America_Cayenne = "America/Cayenne",
      America_Chicago = "America/Chicago",
      America_Chihuahua = "America/Chihuahua",
      America_Costa_Rica = "America/Costa_Rica",
      America_Creston = "America/Creston",
      America_Cuiaba = "America/Cuiaba",
      America_Curacao = "America/Curacao",
      America_Danmarkshavn = "America/Danmarkshavn",
      America_Dawson = "America/Dawson",
      America_Dawson_Creek = "America/Dawson_Creek",
      America_Denver = "America/Denver",
      America_Detroit = "America/Detroit",
      America_Edmonton = "America/Edmonton",
      America_Eirunepe = "America/Eirunepe",
      America_El_Salvador = "America/El_Salvador",
      America_Fort_Nelson = "America/Fort_Nelson",
      America_Fortaleza = "America/Fortaleza",
      America_Glace_Bay = "America/Glace_Bay",
      America_Godthab = "America/Godthab",
      America_Goose_Bay = "America/Goose_Bay",
      America_Grand_Turk = "America/Grand_Turk",
      America_Guatemala = "America/Guatemala",
      America_Guayaquil = "America/Guayaquil",
      America_Guyana = "America/Guyana",
      America_Halifax = "America/Halifax",
      America_Havana = "America/Havana",
      America_Hermosillo = "America/Hermosillo",
      America_Indiana_Indianapolis = "America/Indiana/Indianapolis",
      America_Indiana_Knox = "America/Indiana/Knox",
      America_Indiana_Marengo = "America/Indiana/Marengo",
      America_Indiana_Petersburg = "America/Indiana/Petersburg",
      America_Indiana_Tell_City = "America/Indiana/Tell_City",
      America_Indiana_Vevay = "America/Indiana/Vevay",
      America_Indiana_Vincennes = "America/Indiana/Vincennes",
      America_Indiana_Winamac = "America/Indiana/Winamac",
      America_Inuvik = "America/Inuvik",
      America_Iqaluit = "America/Iqaluit",
      America_Jamaica = "America/Jamaica",
      America_Juneau = "America/Juneau",
      America_Kentucky_Louisville = "America/Kentucky/Louisville",
      America_Kentucky_Monticello = "America/Kentucky/Monticello",
      America_La_Paz = "America/La_Paz",
      America_Lima = "America/Lima",
      America_Los_Angeles = "America/Los_Angeles",
      America_Maceio = "America/Maceio",
      America_Managua = "America/Managua",
      America_Manaus = "America/Manaus",
      America_Martinique = "America/Martinique",
      America_Matamoros = "America/Matamoros",
      America_Mazatlan = "America/Mazatlan",
      America_Menominee = "America/Menominee",
      America_Merida = "America/Merida",
      America_Metlakatla = "America/Metlakatla",
      America_Mexico_City = "America/Mexico_City",
      America_Miquelon = "America/Miquelon",
      America_Moncton = "America/Moncton",
      America_Monterrey = "America/Monterrey",
      America_Montevideo = "America/Montevideo",
      America_Nassau = "America/Nassau",
      America_New_York = "America/New_York",
      America_Nipigon = "America/Nipigon",
      America_Nome = "America/Nome",
      America_Noronha = "America/Noronha",
      America_North_Dakota_Beulah = "America/North_Dakota/Beulah",
      America_North_Dakota_Center = "America/North_Dakota/Center",
      America_North_Dakota_New_Salem = "America/North_Dakota/New_Salem",
      America_Ojinaga = "America/Ojinaga",
      America_Panama = "America/Panama",
      America_Pangnirtung = "America/Pangnirtung",
      America_Paramaribo = "America/Paramaribo",
      America_Phoenix = "America/Phoenix",
      America_Port_of_Spain = "America/Port_of_Spain",
      America_Port_au_Prince = "America/Port-au-Prince",
        America_Porto_Velho = "America/Porto_Velho",
        America_Puerto_Rico = "America/Puerto_Rico",
        America_Punta_Arenas = "America/Punta_Arenas",
        America_Rainy_River = "America/Rainy_River",
        America_Rankin_Inlet = "America/Rankin_Inlet",
        America_Recife = "America/Recife",
        America_Regina = "America/Regina",
        America_Resolute = "America/Resolute",
        America_Rio_Branco = "America/Rio_Branco",
        America_Santarem = "America/Santarem",
        America_Santiago = "America/Santiago",
        America_Santo_Domingo = "America/Santo_Domingo",
        America_Sao_Paulo = "America/Sao_Paulo",
        America_Scoresbysund = "America/Scoresbysund",
        America_Sitka = "America/Sitka",
        America_St_Johns = "America/St_Johns",
        America_Swift_Current = "America/Swift_Current",
        America_Tegucigalpa = "America/Tegucigalpa",
        America_Thule = "America/Thule",
        America_Thunder_Bay = "America/Thunder_Bay",
        America_Tijuana = "America/Tijuana",
        America_Toronto = "America/Toronto",
        America_Vancouver = "America/Vancouver",
        America_Whitehorse = "America/Whitehorse",
        America_Winnipeg = "America/Winnipeg",
        America_Yakutat = "America/Yakutat",
        America_Yellowknife = "America/Yellowknife",
        Antarctica_Casey = "Antarctica/Casey",
        Antarctica_Davis = "Antarctica/Davis",
        Antarctica_DumontDUrville = "Antarctica/DumontDUrville",
          Antarctica_Macquarie = "Antarctica/Macquarie",
          Antarctica_Mawson = "Antarctica/Mawson",
          Antarctica_Palmer = "Antarctica/Palmer",
          Antarctica_Rothera = "Antarctica/Rothera",
          Antarctica_Syowa = "Antarctica/Syowa",
          Antarctica_Troll = "Antarctica/Troll",
          Antarctica_Vostok = "Antarctica/Vostok",
          Asia_Almaty = "Asia/Almaty",
          Asia_Amman = "Asia/Amman",
          Asia_Anadyr = "Asia/Anadyr",
          Asia_Aqtau = "Asia/Aqtau",
          Asia_Aqtobe = "Asia/Aqtobe",
          Asia_Ashgabat = "Asia/Ashgabat",
          Asia_Atyrau = "Asia/Atyrau",
          Asia_Baghdad = "Asia/Baghdad",
          Asia_Baku = "Asia/Baku",
          Asia_Bangkok = "Asia/Bangkok",
          Asia_Barnaul = "Asia/Barnaul",
          Asia_Beirut = "Asia/Beirut",
          Asia_Bishkek = "Asia/Bishkek",
          Asia_Brunei = "Asia/Brunei",
          Asia_Chita = "Asia/Chita",
          Asia_Choibalsan = "Asia/Choibalsan",
          Asia_Colombo = "Asia/Colombo",
          Asia_Damascus = "Asia/Damascus",
          Asia_Dhaka = "Asia/Dhaka",
          Asia_Dili = "Asia/Dili",
          Asia_Dubai = "Asia/Dubai",
          Asia_Dushanbe = "Asia/Dushanbe",
          Asia_Famagusta = "Asia/Famagusta",
          Asia_Gaza = "Asia/Gaza",
          Asia_Hebron = "Asia/Hebron",
          Asia_Ho_Chi_Minh = "Asia/Ho_Chi_Minh",
          Asia_Hong_Kong = "Asia/Hong_Kong",
          Asia_Hovd = "Asia/Hovd",
          Asia_Irkutsk = "Asia/Irkutsk",
          Asia_Jakarta = "Asia/Jakarta",
          Asia_Jayapura = "Asia/Jayapura",
          Asia_Jerusalem = "Asia/Jerusalem",
          Asia_Kabul = "Asia/Kabul",
          Asia_Kamchatka = "Asia/Kamchatka",
          Asia_Karachi = "Asia/Karachi",
          Asia_Kathmandu = "Asia/Kathmandu",
          Asia_Khandyga = "Asia/Khandyga",
          Asia_Kolkata = "Asia/Kolkata",
          Asia_Krasnoyarsk = "Asia/Krasnoyarsk",
          Asia_Kuala_Lumpur = "Asia/Kuala_Lumpur",
          Asia_Kuching = "Asia/Kuching",
          Asia_Macau = "Asia/Macau",
          Asia_Magadan = "Asia/Magadan",
          Asia_Makassar = "Asia/Makassar",
          Asia_Manila = "Asia/Manila",
          Asia_Nicosia = "Asia/Nicosia",
          Asia_Novokuznetsk = "Asia/Novokuznetsk",
          Asia_Novosibirsk = "Asia/Novosibirsk",
          Asia_Omsk = "Asia/Omsk",
          Asia_Oral = "Asia/Oral",
          Asia_Pontianak = "Asia/Pontianak",
          Asia_Pyongyang = "Asia/Pyongyang",
          Asia_Qatar = "Asia/Qatar",
          Asia_Qostanay = "Asia/Qostanay",
            Asia_Qyzylorda = "Asia/Qyzylorda",
            Asia_Riyadh = "Asia/Riyadh",
            Asia_Sakhalin = "Asia/Sakhalin",
            Asia_Samarkand = "Asia/Samarkand",
            Asia_Seoul = "Asia/Seoul",
            Asia_Shanghai = "Asia/Shanghai",
            Asia_Singapore = "Asia/Singapore",
            Asia_Srednekolymsk = "Asia/Srednekolymsk",
            Asia_Taipei = "Asia/Taipei",
            Asia_Tashkent = "Asia/Tashkent",
            Asia_Tbilisi = "Asia/Tbilisi",
            Asia_Tehran = "Asia/Tehran",
            Asia_Thimphu = "Asia/Thimphu",
            Asia_Tokyo = "Asia/Tokyo",
            Asia_Tomsk = "Asia/Tomsk",
            Asia_Ulaanbaatar = "Asia/Ulaanbaatar",
            Asia_Urumqi = "Asia/Urumqi",
            Asia_Ust_Nera = "Asia/Ust-Nera",
              Asia_Vladivostok = "Asia/Vladivostok",
              Asia_Yakutsk = "Asia/Yakutsk",
              Asia_Yangon = "Asia/Yangon",
              Asia_Yekaterinburg = "Asia/Yekaterinburg",
              Asia_Yerevan = "Asia/Yerevan",
              Atlantic_Azores = "Atlantic/Azores",
              Atlantic_Bermuda = "Atlantic/Bermuda",
              Atlantic_Canary = "Atlantic/Canary",
              Atlantic_Cape_Verde = "Atlantic/Cape_Verde",
              Atlantic_Faroe = "Atlantic/Faroe",
              Atlantic_Madeira = "Atlantic/Madeira",
              Atlantic_Reykjavik = "Atlantic/Reykjavik",
              Atlantic_South_Georgia = "Atlantic/South_Georgia",
              Atlantic_Stanley = "Atlantic/Stanley",
              Australia_Adelaide = "Australia/Adelaide",
              Australia_Brisbane = "Australia/Brisbane",
              Australia_Broken_Hill = "Australia/Broken_Hill",
              Australia_Currie = "Australia/Currie",
              Australia_Darwin = "Australia/Darwin",
              Australia_Eucla = "Australia/Eucla",
              Australia_Hobart = "Australia/Hobart",
              Australia_Lindeman = "Australia/Lindeman",
              Australia_Lord_Howe = "Australia/Lord_Howe",
              Australia_Melbourne = "Australia/Melbourne",
              Australia_Perth = "Australia/Perth",
              Australia_Sydney = "Australia/Sydney",
              Europe_Amsterdam = "Europe/Amsterdam",
              Europe_Andorra = "Europe/Andorra",
              Europe_Astrakhan = "Europe/Astrakhan",
              Europe_Athens = "Europe/Athens",
              Europe_Belgrade = "Europe/Belgrade",
              Europe_Berlin = "Europe/Berlin",
              Europe_Brussels = "Europe/Brussels",
              Europe_Bucharest = "Europe/Bucharest",
              Europe_Budapest = "Europe/Budapest",
              Europe_Chisinau = "Europe/Chisinau",
              Europe_Copenhagen = "Europe/Copenhagen",
              Europe_Dublin = "Europe/Dublin",
              Europe_Gibraltar = "Europe/Gibraltar",
              Europe_Helsinki = "Europe/Helsinki",
              Europe_Istanbul = "Europe/Istanbul",
              Europe_Kaliningrad = "Europe/Kaliningrad",
              Europe_Kiev = "Europe/Kiev",
              Europe_Kirov = "Europe/Kirov",
              Europe_Lisbon = "Europe/Lisbon",
              Europe_London = "Europe/London",
              Europe_Luxembourg = "Europe/Luxembourg",
              Europe_Madrid = "Europe/Madrid",
              Europe_Malta = "Europe/Malta",
              Europe_Minsk = "Europe/Minsk",
              Europe_Monaco = "Europe/Monaco",
              Europe_Moscow = "Europe/Moscow",
              Europe_Oslo = "Europe/Oslo",
              Europe_Paris = "Europe/Paris",
              Europe_Prague = "Europe/Prague",
              Europe_Riga = "Europe/Riga",
              Europe_Rome = "Europe/Rome",
              Europe_Samara = "Europe/Samara",
              Europe_Saratov = "Europe/Saratov",
              Europe_Simferopol = "Europe/Simferopol",
              Europe_Sofia = "Europe/Sofia",
              Europe_Stockholm = "Europe/Stockholm",
              Europe_Tallinn = "Europe/Tallinn",
              Europe_Tirane = "Europe/Tirane",
              Europe_Ulyanovsk = "Europe/Ulyanovsk",
              Europe_Uzhgorod = "Europe/Uzhgorod",
              Europe_Vienna = "Europe/Vienna",
              Europe_Vilnius = "Europe/Vilnius",
              Europe_Volgograd = "Europe/Volgograd",
              Europe_Warsaw = "Europe/Warsaw",
              Europe_Zaporozhye = "Europe/Zaporozhye",
              Europe_Zurich = "Europe/Zurich",
              Indian_Chagos = "Indian/Chagos",
              Indian_Christmas = "Indian/Christmas",
              Indian_Cocos = "Indian/Cocos",
              Indian_Kerguelen = "Indian/Kerguelen",
              Indian_Mahe = "Indian/Mahe",
              Indian_Maldives = "Indian/Maldives",
              Indian_Mauritius = "Indian/Mauritius",
              Indian_Reunion = "Indian/Reunion",
              Pacific_Apia = "Pacific/Apia",
              Pacific_Auckland = "Pacific/Auckland",
              Pacific_Bougainville = "Pacific/Bougainville",
              Pacific_Chatham = "Pacific/Chatham",
              Pacific_Chuuk = "Pacific/Chuuk",
              Pacific_Easter = "Pacific/Easter",
              Pacific_Efate = "Pacific/Efate",
              Pacific_Enderbury = "Pacific/Enderbury",
              Pacific_Fakaofo = "Pacific/Fakaofo",
              Pacific_Fiji = "Pacific/Fiji",
              Pacific_Funafuti = "Pacific/Funafuti",
              Pacific_Galapagos = "Pacific/Galapagos",
              Pacific_Gambier = "Pacific/Gambier",
              Pacific_Guadalcanal = "Pacific/Guadalcanal",
              Pacific_Guam = "Pacific/Guam",
              Pacific_Honolulu = "Pacific/Honolulu",
              Pacific_Kiritimati = "Pacific/Kiritimati",
              Pacific_Kosrae = "Pacific/Kosrae",
              Pacific_Kwajalein = "Pacific/Kwajalein",
              Pacific_Majuro = "Pacific/Majuro",
              Pacific_Marquesas = "Pacific/Marquesas",
              Pacific_Nauru = "Pacific/Nauru",
              Pacific_Niue = "Pacific/Niue",
              Pacific_Norfolk = "Pacific/Norfolk",
              Pacific_Noumea = "Pacific/Noumea",
              Pacific_Pago_Pago = "Pacific/Pago_Pago",
              Pacific_Palau = "Pacific/Palau",
              Pacific_Pitcairn = "Pacific/Pitcairn",
              Pacific_Pohnpei = "Pacific/Pohnpei",
              Pacific_Port_Moresby = "Pacific/Port_Moresby",
              Pacific_Rarotonga = "Pacific/Rarotonga",
              Pacific_Tahiti = "Pacific/Tahiti",
              Pacific_Tarawa = "Pacific/Tarawa",
              Pacific_Tongatapu = "Pacific/Tongatapu",
              Pacific_Wake = "Pacific/Wake",
              Pacific_Wallis = "Pacific/Wallis"
  }